import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import Link from "next/link";
import {
  RiWhatsappFill,
  RiLinkedinBoxFill,
  RiGithubFill,
} from "react-icons/ri";
import { MdEmail } from "react-icons/md";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="height-full">
        <div className="avatar-frame">
          <Image
            priority
            className="avatar"
            fill
            alt="me"
            src="/profile_picture.jpeg"
          ></Image>
        </div>
        <div className="title">Walber Zaldivar</div>
        <div className="subtitle">Software Developer</div>
        <Link className="title" href="https://wa.me/59895059121">
          <RiWhatsappFill />
        </Link>
        <Link href="https://linkedin.com/in/walber-zaldivar-herrera">
          <RiLinkedinBoxFill />
        </Link>
        <Link href="mailto:walber.zaldivar@gmail.com">
          <MdEmail />
        </Link>
        <Link href="mailto:walber.zaldivar@gmail.com">
          <RiGithubFill />
        </Link>
      </div>
    </>
  );
}
