name: Docker Image CI

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "release" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Determine tag
      id: determine-tag
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/release" ]] || [[ "${{ github.event.pull_request.base.ref }}" == "release" ]]; then
          echo "TAG=release" >> $GITHUB_ENV
        else
          echo "TAG=latest" >> $GITHUB_ENV
        fi

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Login to registry
      if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_HOST }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name == 'push' }}
        tags: ${{ secrets.REGISTRY_HOST }}/wzaldivar-profile:${{ env.TAG }}
